### ISSUE TITLE
Live Captions / Subtitles for the Deaf and hard-of-hearing (SDH) / intralingual subtitles

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#12]
Draft currently has almost nothing on live captions -- just a little in the **[Scope](https://deploy-preview-7--wai-media-guide.netlify.com/design-develop/media/captions/#scope)** section.

@eoncins , What suggestions do you have for guidance on live captions that we might want to include?

**Comment by eoncins** [comment]
Dear Shawn,


For live subtitling in real-time there are different sources available.


They can be either provided by a professional mainly using standard QWERTY keyboards, Velotype and the two most common approaches, namely stenography and respeaking.

The document http://galmaobservatory.eu/areas/live-subtitling-respeaking/ provides an insight about live subtitling.


Also YouTube provides the possibility to provide automatic captions using their automatic voice recognition system which is getting more and more accurate in terms of quality.


Here the YouTube (Google) guide:


https://support.google.com/youtube/answer/6373554?hl=en



Since more and more events are streamed online through different platforms from my point of view it is worth to provide a more extensive explanation. I can help if you agree.


I would surely include:

- Methods of live subtitling (respeaking, QWERTY, velotype, stenography)

- Automatic captions using voice recognition systems


What do you think?


Best,

Estel·la


Edifici MRA 126  - Campus UAB
08193 Bellaterra
Barcelona
T. +34 610 655 149

orcid.org/0000-0002-0291-3036<https://orcid.org/0000-0002-0291-3036>
http://grupsderecerca.uab.cat/transmedia/
________________________________
De: shawn_slh <notifications@github.com>
Enviat el: dilluns, 10 de juny de 2019 20:42:43
Per a: w3c/wai-media-guide
A/c: Estel·la Oncins Noguer; Mention
Tema: [w3c/wai-media-guide] Live Captions / Subtitles for the Deaf and hard-of-hearing (SDH) intralingual subtitles (#12)


Draft currently has almost nothing on live captions -- just a little in the Scope<https://deploy-preview-7--wai-media-guide.netlify.com/design-develop/media/captions/#scope> section.

@eoncins<https://github.com/eoncins> , What suggestions do you have for guidance on live captions that we might want to include?

**Comment by shawna-slh** [comment]
@eoncins 

Thank you for the additional information.

> - Automatic captions using voice recognition systems

We currently have a section that addresses this: [Automatic Captions are Not Sufficient](https://wai-media-guide.netlify.com/design-develop/media/captions/#automatic-captions-are-not-sufficient). Please see the text in that section. Do you have any comments on that? If so, please put them in a [new issue on automatic captions](https://github.com/w3c/wai-media-guide/issues/new?title=Automatic%20Captions).

<hr>

> Methods of live subtitling (respeaking, QWERTY, velotype, stenography)

It is my understanding that high-quality live captioning realistically can only be done by trained professionals. That is, few people have the tools and skills to accurately caption live content with sufficient accuracy. I wonder if our **[target audience](https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#Requirements_Analysis)** would find details on the methods very useful, or if it would be unnecessary clutter to them?

I definitely agree that we need to be clear that captions are needed for live content. I have edited the draft so "Live Captions" section shows up in the [contents list](https://wai-media-guide.netlify.com/design-develop/media/captions/).

I also added some information about the option for the CART person to be remote. (That, I think, is something that our target audience would want to know. :-)

I wonder if the text that is there is enough for this resource, or if we need to say more? 

Please put any additional thoughts on that here. :-)

**Question** for you (and others!): Is the terminology listed sufficiently clear across the world, or might we want to include other variations?

Thanks!

**Comment by eoncins** [comment]
Agree that high-quality live captioning can only be done by trained professionals and that target audiences may not need the details on methods. I would suggest to add some information regarding setup.

"The biggest challenge with speech recognition technology is accuracy, which can only be achieved in  in optimum situations. There are some speech recognition systems currently available in the market such as Dragon Naturally Speaking (https://www.nuance.com/dragon.html). In a process called respeaking, the user speaks along with the audio, repeating what the speaker is saying. The respeaker has to train the software to recognize his/her speech patterns, audio quality and acoustics of the recording environment have to be excellent, and distracting background noises have to be reduced to minimum levels. Few audiovisual media meet these criteria. While fully automated captioning may not currently be sufficient, speech recognition can play a significant role in helping to produce a transcript and create captions/subtitles from an existing transcript."

Regarding terminology: According to ITU: "communication access real time translation (CART): CART is a North American term for real time captioning" I would definitely add the terms "realtime captioning/subtitling".

**Comment by shawna-slh** [comment]
> I would definitely add the terms "realtime captioning

+1
Done.

> I would suggest to add some information regarding setup. ...

I agree fully that this is interesting to some readers. I'm just thinking that for most of the [target use cases and tasks for this resource](https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#Requirements_Analysis), it is more information than then really need, and we don't want to clutter the resource with too much text.

I'll think some more about it as I work on the transcripts page to better address the do-it-yourself podcaster making their own transcripts ... :-)

**Comment by eoncins** [comment]
+1 agree that terminology has to be considered in order to be consistent with the information provided but is out of the scope of the target use cases.

**Comment by shawna-slh** [comment]
@eoncins , Thanks again for your input!

I've added a new page: [Transcribing Audio to Text](https://wai-media-guide.netlify.com/design-develop/media/transcribing/)

I will open a new issue on how much detail to include in our resource, and on linking to outside resources for more details.

**Comment by eoncins** [comment]
Hello Shawn,


Thanks a lot.


Are you planing also to include recommendations about the type of font (non sans serif), size, use of background, verbatim of block, positioning...


I will wait for the open issue in GitHub.


Best,


Estel·la Oncins Noguer
Post Doctoral Research Fellow TransMedia Catalonia
Edifici MRA 126  - Campus UAB
08193 Bellaterra
Barcelona
T. +34 610 655 149

orcid.org/0000-0002-0291-3036<https://orcid.org/0000-0002-0291-3036><https://orcid.org/0000-0002-0291-3036>
http://grupsderecerca.uab.cat/transmedia<http://grupsderecerca.uab.cat/transmedia/>
<http://grupsderecerca.uab.cat/transmedia/>
<http://grupsderecerca.uab.cat/transmedia/>

<http://grupsderecerca.uab.cat/transmedia/><http://grupsderecerca.uab.cat/transmedia/>

________________________________
De: shawn_slh <notifications@github.com>
Enviat el: dijous, 11 de juliol de 2019 5:13:55
Per a: w3c/wai-media-guide
A/c: Estel·la Oncins Noguer; Mention
Tema: Re: [w3c/wai-media-guide] Live Captions / Subtitles for the Deaf and hard-of-hearing (SDH) / intralingual subtitles (#12)


@eoncins<https://github.com/eoncins> , Thanks again for your input!

I've added a new page: Transcribing Audio to Text<https://wai-media-guide.netlify.com/design-develop/media/transcribing/>

I will open a new issue on how much detail to include in our resource, and on linking to outside resources for more details.

**Comment by shawna-slh** [comment]
> Are you planing also to include recommendations about the type of font (non sans serif), size, use of background, verbatim of block, positioning...

Here is an open issue for you to comment on that :) [Caption display control](https://github.com/w3c/wai-media-guide/issues/28)

**Comment by eoncins** [comment]
Hello Shawn,


It is true that most of the times it depends on the video player. In fact, it also depends if the subtitle/captions are an extra file (.WebVTT or .srt) or if they are burn-in.


For instance in YouTube the users can adapt the subtitles/captions to their needs "https://support.google.com/youtube/answer/100078" because the player allows them to do so if captions/subtitles are available.


However, if the subtitles are burn-in then font, size and background has to be taken in consideration.


In the case of live captions there are different platforms which can be used as secondary screens that allow end user to select their preferences in terms of font, size and background.


Best,


Estel·la


Estel·la Oncins Noguer
Post Doctoral Research Fellow TransMedia Catalonia
Edifici MRA 126  - Campus UAB
08193 Bellaterra
Barcelona
T. +34 610 655 149

orcid.org/0000-0002-0291-3036<https://orcid.org/0000-0002-0291-3036><https://orcid.org/0000-0002-0291-3036>
http://grupsderecerca.uab.cat/transmedia<http://grupsderecerca.uab.cat/transmedia/>
<http://grupsderecerca.uab.cat/transmedia/>
<http://grupsderecerca.uab.cat/transmedia/>

<http://grupsderecerca.uab.cat/transmedia/><http://grupsderecerca.uab.cat/transmedia/>

________________________________
De: shawn_slh <notifications@github.com>
Enviat el: dijous, 11 de juliol de 2019 22:01:36
Per a: w3c/wai-media-guide <wai-media-guide@noreply.github.com>
A/c: Estel·la Oncins Noguer <Estella.Oncins@uab.cat>; Mention <mention@noreply.github.com>
Tema: Re: [w3c/wai-media-guide] Live Captions / Subtitles for the Deaf and hard-of-hearing (SDH) / intralingual subtitles (#12)


Are you planing also to include recommendations about the type of font (non sans serif), size, use of background, verbatim of block, positioning...

Here is an open issue for you to comment on that :) Caption display control<https://github.com/w3c/wai-media-guide/issues/28>
