### ISSUE TITLE
[confirm edits published] Incorrect advice for video-only and transcripts

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wai-media-guide#125]
On https://www.w3.org/WAI/media/av/transcripts/#checklist the guide currently states:

> **Video-only (no audio content):**
> For pre-recorded and live:
> Transcripts are not needed because there is no audio information.

This seems incorrect, or at least misleading. Yes, lacking any audio, there's no need for an audio transcript. However, a media alternative that described the visual aspect is still needed (roughly what the guide here alludes to earlier with "Descriptive transcript", but without any audio transcription).

Per 1.2.1 Audio-only and Video-only (Prerecorded) https://www.w3.org/TR/WCAG21/#audio-only-and-video-only-prerecorded

> **Prerecorded Video-only**
> Either an **alternative for time-based media** or an audio track is provided that presents equivalent information for prerecorded video-only content.

https://www.w3.org/TR/WCAG21/#dfn-alternative-for-time-based-media

> **alternative for time-based media**
> document including correctly sequenced text descriptions of time-based visual and auditory information and providing a means for achieving the outcomes of any time-based interaction

While it seems the guide here is trying to primarily address audio transcripts, it would at least be good to mention/cross-reference the fact that video-only content will also still need a media alternative.

**Comment by shawna-slh** [comment]
Agree!

I made a quick fix for now. https://github.com/w3c/wai-media-guide/pull/128/files

I'm leaving this issue open since that edit needs WG review, and I want to think more about if we want to tweak it here, and/or edit related info elsewhere.

(p.s. sooo sorry that we missed this GitHub issue earlier)

Thanks, Patrick!

**Comment by shawna-slh** [comment]
This has needs AG WG review. (was previously listed in EOWG review) Can be reviewed here:
* [Diff of markup](https://github.com/w3c/wai-media-guide/pull/128/files)
* In resource:  [In Transcripts, under Does My Media Need a Transcript?, Video-only (no audio content): ](https://www.w3.org/WAI/media/av/transcripts/#checklist-vo) -- all 4 bullets in that section.

**I encourage anyone to review it and put a +1 in this issue or otherwise indicate their review comments.**
Thanks!

**Comment by shawna-slh** [comment]
[reviewed by AG WG](https://lists.w3.org/Archives/Public/w3c-wai-gl/2021JanMar/0036.html)
