### ISSUE TITLE
[confirm edits published] Audio Description requirement unclear

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#153]
In: Checklists for Audio and Video > Video Checklists > Pre-Recorded Video

> - Audio description of the visual information (A/AA)
> - Descriptive transcript (AAA) (If you have a descriptive transcript, you do not need an additional transcript of only audio information from the previous question.)

It is not clear from this checklist that a text transcript is sufficient as well, it seems that audio description is required to meet WCAG 2 Level A/AA.

**Comment by nitedog** [comment]
Same of page Audio Description of Visual Information, it seems to indicate that audio description is the only way to meet WCAG 2 Level A/AA.

**Comment by shawna-slh** [comment]
* Success Criterion 1.2.3 Audio Description or Media Alternative (Prerecorded) (Level A) says
can have *either* audio description or descriptive transcript.
* Success Criterion 1.2.5 Audio Description (Prerecorded) (Level AA) says
has to have audio description.

So:
* For Level A, can have *either* audio description _or_ *descriptive* transcript.
* For Level AA, has to have audio description.

I’ve better communicated that in both pages.
* [diff](https://github.com/w3c/wai-media-guide/pull/156/files)

**Comment by shawna-slh** [comment]
I made fix now, since important. Can be reviewed here:
* [Diff of markup](https://github.com/w3c/wai-media-guide/pull/156/files)
* [In Planning Audio and Video Media, under Checklists for Audio and Video, Video Checklists, Pre-Recorded Video](https://www.w3.org/WAI/media/av/planning/#checklist-vp) -- the first 2 bullets under "Does the video have visual information that is needed to understand the content?"
* [In Audio Description of Visual Information, under Does My Media Need Description?, Video:](/media/av/description/#checklist-video) -- the second 2 bullets under "For pre-recorded:"

I'm leaving this issue open since that edit needs AG & EO WG review.

**I encourage anyone to review it and put a +1 in this issue or otherwise indicate their review comments.**

**Comment by nitedog** [comment]
Looks good to me, thanks!

**Comment by bruce-usab** [comment]
+1, reviewed.

In particular I will express my appreciation for the acknowledgement that audio description is not _required_ by WCAG for live broadcasts, but that it is _needed_ by people who are blind.  We frequently make this point with 508 that there are accessibility needs (and disability civil rights) that are not perfectly captured by the regulation.  Asking (or reminding) presenters to assume that many viewers _cannot_ see their screen is a very easy accommodation.

**Comment by shawna-slh** [comment]
[reviewed by AG WG](https://lists.w3.org/Archives/Public/w3c-wai-gl/2021JanMar/0036.html)
