### ISSUE TITLE
[coding] images in box titles

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#32]
Hey @yatil ,

Can we put images in the title of the include boxes? (the couple things I tried didn't work)

For example, see https://wai-media-guide.netlify.com/design-develop/media/planning/#checklists

p.s. those images are just rough concepts -- will have images in SVG when done. :-)

**Comment by yatil** [comment]
You should only use one of the specified icons in 
https://w3c.github.io/wai-website-components/components/detail/icons--default.html

I have added the icons to the box headings.

Note that they **violate the style guide** and I cannot publish them like this. It uses two icons interspersed with text which makes it incredible hard to read. Combine both icons into one and then submit it to be included in the icon set. That way the icons are on the left and hopefully the same width so that basic readability is given.

**Comment by shawna-slh** [comment]
Thank you for adding the icons to the box headings.

We're still in the **playing-and-exploring-ideas** stage. Not even close to the ask-how-feasible-to-implement-before-making-decisions stage. :-)

EOWG did not like two icons together -- but I'll put that back for comparison for additional discussion.
