### ISSUE TITLE
(low) [Planning page] replace "things"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#41]
> This section covers things like podcasts that don’t have video.

Maybe replace "things" with "audio-only", to help explain the term?

**Comment by yatil** [comment]
I struggle why we need to explain “audio-only” at all. That seems pretty self-explanatory to me. Maybe just remove the sentence.

**Comment by shawna-slh** [comment]
changed to:
> This section covers audio-only media, like podcasts that don't have video.

@yatil Yeah, I'm not sure. It's totally clear to us who are well versed in WCAG. And maybe it's clear to others, too, since it's not jargon and just common words. I'm still thinking it's worth the one short sentence to be very clear. Also, I think the resource focuses a lot on video, and want to make sure that **podcasters easily see what is relevant to them**.

**Comment by nitedog** [comment]
I agree that many readers do not understand "audio-only" at first.
