### ISSUE TITLE
Feedback of Review for April 26th

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#5]
Sorry for not getting back earlier, here are some random observations. Feel free to just close the issue, no response needed.

* Decide on either calling it `Audio & Video` or `Media`, currently both are used and it makes it harder to read if we use both terms interchangeably.

* Condense intro page _or_ get rid of sub-pages: The intro page has long descriptions of what captions (for example) are, the Captions page itself does not add too much to the understanding what captions are. I think the into page should just be a listicle. That way it is easy for people who already know how to do it to find out what to do and not forget an aspect. Example (I don’t know why Github insists on roman numerals for the list): 

  > Here are the five things you need to look into for accessible Audio & Video: 
  > 
  > 1. **Captions** is text that is displayed alongside audio for people who cannot hear or understand the audio. 
  > 2. **Transcripts** is the full text of the audio content and also important visual cues. 
  > 3. **Audio Description** is audio that tells users who cannot see a video what is happening on the screen. 
  > 4. **Sign Language** translates the audio into a language that is easy to understand for Deaf people. 
  > 5. Avoid **Flashing and Blinking** as some people can have reactions such as seizures._

* Separate “Managing Media” and “Standards” – There is no need for someone to manage standards (which I first read when it said “Manage Media & Standards”). At first glance, I’m unsure what ”Manage Media” means in this context, colloquially managing media means categorizing MP3 files or videos. We mean “manage the process of making your videos accessible” in which case I think the Overview page as a listicle should give managers enough material to structure the work. (That is the task of the Tutorial Overview pages as well.)

* **“Audio and Video Content” (-> Audio & Video Content)**: I don’t have a good suggestion but I think it is hard to understand what this page is for at the first glance as the whole guide is about audio and video content. Maybe something like “Inaccessible Audio and Visual Effects” as this would be something that people would want to read.

* **Description**: Should be “Audio Description”, lots of content. Instead of going into terminology, I suggest using “audio-described video” instead of just ”described video”.

* **Description**: 

  > This page addresses common types of videos designed for the web such as instructional videos, training videos, recordings of presentations, and such. It does not address all the issues around full-feature movies, television shows, and such.

  Why? I don’t think it differs much. Instead of out-scoping this why not have a paragraph that says something like: “When adding audio description to a movie or television show, the audio description needs to be implemented in a way that keeps the tension of the movie or TV show intact.” 

* **Description**: Tables with more than two columns are hard to make responsive. We need to look into their responsive fallback.

* **Description**: Instead of using text to describe audio-described vs. non-described video, add a video where you have the scene of the video without audio description and then the same scene with the audio description. A video says more than 1000 images.

* **Description**: The word developing used at the end feels weird ”Developing Integrated Description”. Maybe that is my web development background, but I think Create would be better or just ”Integrated Description”, “Description in a Separate Audio File Only”, “Developing a Separate Described Video”

* **Description**: The steps in developing look all very similar. I think there is a lot of potential for condensing.

* **Captions**: Unsure about mentioning YouTube as the (only?) example to go for captioning.

* **Captions**:

  > For most web content, it is acceptable to leave out non-substantive text to make the captions easier to process 

  I know that a lot of disability organizations do not agree with this as users cannot determine if the spoken word was deliberately left out or not. At least the use of `(…)` is recommended, if not adding the whole text.

* **Captions:**

  > If there is speech that is not at all relevant, indicate that it has been excluded from the captions. For example: _[participants discuss the weather while the presenter reboots his computer]_

  Again, many disability organizations think that the decision, if something is not relevant, should be made by the user, not by the video publisher.

* **Captions:** Unsure if we need file formats here, it depends on what media player you use and how well it is understood.

* **Media Player:** List first what aspects a video player needs to support (Keyboard navigation, Audio Descriptions, Captions, Transcripts…) 

* **Media Player:** Unsure if we want to list commercial players. There is this overview of media players: http://videosws.praegnanz.de

* **?User Experience:** I think those aspects can be covered in the “What a media player needs to do” section on the media player page.

* **In General**: Images need to be bigger and easier to read.

* **In General**: Some “more information” text seems to have little contrast to the background.

* (very minor at this point) **In General**: Several elements need to be adjusted according to our design principles and guidelines. (boxes in a different color, boxes without headings…)

**Again: Feel free to just close the issue, no response needed.**

**Comment by shawna-slh** [comment]
> Decide on either calling it `Audio & Video` or `Media`, currently both are used and it makes it harder to read if we use both terms interchangeably.

Different people are looking for different terms (+ "audio-visual"). I think we need to have most common terms in the titles &/or headings for SEO and so people are comfortable that they're in the right place. Then we *might* decide to use single terms throughout, such as we're leaning towards with "captions"( https://github.com/w3c/wai-media-guide/issues/10).

>  **Description**: Should be “Audio Description”, lots of content. Instead of going into terminology, I suggest using “audio-described video” instead of just ”described video”.

Some people find "audio description" and “audio-described video” completely confusing – because it's description of the visual information, not description of the audio information! 

My feeling is that the current wording will be *understandable* to:
* people who are used to "audio description"<br>and people for whom that is totally wrong and confusing
* people who are used to "described video" (e.g., Canadians)

EOWG can talk more about this if it comes up again as an issue.

> "This page addresses common types of videos designed for the web such as instructional videos, training videos, recordings of presentations, and such. It does not address all the issues around full-feature movies, television shows, and such."
> Why? I don’t think it differs much. Instead of out-scoping this why not have a paragraph that says something like: “When adding audio description to a movie or television show, the audio description needs to be implemented in a way that keeps the tension of the movie or TV show intact.”

I'll see what Chris & Estella & others have to say about issues around it being in scope or not. [14](https://github.com/w3c/wai-media-guide/issues/14) Maybe it's all the same considerations so we don't need to mention it at all? Maybe there are a lot more things that we don't want to get into, and so do need to out-scope it?

(In any case, I think "audio description needs to be implemented in a way that keeps the tension of the movie or TV show intact” is also true for some "web video"s, so I don't see why to call it out just for movie or TV shows.)

> **Description**: Tables with more than two columns are hard to make responsive. We need to look into their responsive fallback.

Thanks! ;-)

> **Description**: Instead of using text to describe audio-described vs. non-described video, add a video where you have the scene of the video without audio description and then the same scene with the audio description. A video says more than 1000 images.

Is there text to describe a non-described video?

I love doing an activity in training where I turn off the "screen" during a video with particularly funny visuals, and people really miss the visual information. I think that's a bit too much for this. 

I did add a link to a video that includes audio description of the visual information.

>  **Description**: The word developing used at the end feels weird ”Developing Integrated Description”. Maybe that is my web development background, but I think Create would be better or just ”Integrated Description”, “Description in a Separate Audio File Only”, “Developing a Separate Described Video”

Changed page title from "Creating Audio Description of Visual Information" to just "Audio Description of Visual Information"" (since also covers what you need to know for outsourcing even if not developing yourself). And changed those headings from "Developing…" to "Creating…"

> **Description**: The steps in developing look all very similar. I think there is a lot of potential for condensing.

My thinking is that in any specific case, you will do only *one* of the options. So I *mildly* think condensing would actually make doing only one more complicated.

I put them under a sub-heading of "Options" to make that more clear.

Let's see how it pans out…

> **Captions**: Unsure about mentioning YouTube as the (only?) example to go for captioning.

Yeah. Of course I am extremely aware of the issues of mentioning a specific vendor. Right now I'm thinking that :1. It's by far the most common so it's good to use it as an example so YouTube-users know, 2. It's free (although not available to everyone). 

If you have more specific thoughts, or ideas for others to include, feel free to share!

**Comment by shawna-slh** [comment]
> * **Captions**: For most web content, it is acceptable to leave out non-substantive text to make the captions easier to process

> I know that a lot of disability organizations do not agree with this as users cannot determine if the spoken word was deliberately left out or not. At least the use of `(…)` is recommended, if not adding the whole text.

I think what's there is OK with the caveat and example:

> … while adhering to the tips above. For example, if the speaker says:
> I just got so frustrated (cough, cough) sorry – uhhh what was I saying?…, oh > yea - I got so frustrated with my computer.
> You can caption:
> I just got so frustrated with my computer.

---

 > * **Captions:** If there is speech that is not at all relevant, indicate that it has been excluded from the captions. For example: _[participants discuss the weather while the presenter reboots his computer]_

 > Again, many disability organizations think that the decision, if something is not relevant, should be made by the user, not by the video publisher.

It's a user preference, like how much detail to include in alt text.

I think the example shows something that almost all users would not want fully captioned.

**Comment by shawna-slh** [comment]
[ some things not responded to because they've changed in the draft. :-]

> **Again: Feel free to just close the issue, no response needed.**

Thanks. Closing. :-)
