### ISSUE TITLE
(medium) [Overview] Examples section

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#59]
* I’m unsure if there are benefits of having this section. It is just repeating what is said above. I think a link “To see those accessibility features in action, see our perspective videos, for example this one on captions”.

* Using a video about the topic people want to learn might be counter-productive (then again, people learn about accessibility and all the perspective videos are all about accessibility, so this might not be a concern).

**Comment by shawna-slh** [comment]
> Using a video about the topic people want to learn might be counter-productive (then again, people learn about accessibility and all the perspective videos are all about accessibility, so this might not be a concern).

I'm not sure I agree, but I don't feel strongly, and Shadi said the same thing in https://github.com/w3c/wai-media-guide/issues/39 , so I'll happily change it. :-)

>  I’m unsure if there are benefits of having this section. It is just repeating what is said above. I think a link “To see those accessibility features in action, see our perspective videos, for example this one on captions”.

EOWG said pretty strongly that we should link to or include an example prominently. Therefore, I think it's good to have a heading and in the Page Contents list.

I think the list of things makes it clear what people can look for when they look at the example. Also, we can't say "To see those accessibility features in action" because we don't have sign languages (yet;-).

The list does add vertical scrolling, but I think not much cognitive load at all.
