### ISSUE TITLE
(high) [many pages] Merge Introduction into Summary

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#64]
When the heading of a page is “Captions/Subtitles (in Making Audio and Video Accessible)”, then having “This page provides guidance on understanding and creating captions and subtitles.” is redundant.

the summary on the top should give users the high level take-aways very similar to what is in the introduction section on the pages.

Alternatively, don’t use the summary boxes at all.

**Comment by shawna-slh** [comment]
> Alternatively, don’t use the summary boxes at all.

I tried that on the intro page .... but then didn't like it. Reminder that we added the Summaries and Page Contents at the top of each page of the redesigned website *because of input from usability testing*. Now that we have them of pretty much every page, it seems very odd not to have them.

> high level take-aways very similar to what is in the introduction section on the pages.

I was tempted to *move* some information from the Into to the Summary -- e.g., in the [A/V/ Content page](https://wai-media-guide.netlify.com/design-develop/media/av-content/) -- but that's not right -- there should not be info in a "Summary" that is not in the main body of the page.

I'll leave this open for now and see if I can get brain power to work on ideas for each page summary &/or the big picture approach...

**Comment by shawna-slh** [comment]
I've worked on this several times over the last month. I made several edits. For example [Player](https://wai-media-guide.netlify.com/design-develop/media/player/) page Summary:
> Some media players are not accessible to people with disabilities. There are players developed specifically for accessibility. Usually it’s best to use one of these existing players, rather than code your own.

Yet some of the middle pages still have the construct that you initially commented on.

Some thoughts:
* For most of the middle pages, we want the summaries to communicate:
   * this page has info for managers
   * and for people outsourcing their [captions]
   * and for people doing [captions] in-house
* People who are reading most pages of this resource or using it multiple times, don't need the summaries. For them, short simple summaries makes the summaries easier to "mask out".
* People who "land on a page" e.g., from a search engine, would benefit from a more context at the top of the page. For these readers, I think this:
> <h1>Captions/Subtitles</h1><br><em>(in Making Audio and Video Accessible)</em>
is further explained and clarified by
> This page helps you understand and create captions (also called “subtitles”).

* for some of those pages, I didn't come up with a concise substantive summary beyond what is there


Hopefully you're OK with it. If not, please provide specific suggestions and re-open the issue.

**Comment by shawna-slh** [comment]
Side note: Perhaps for the big picture throughout the website, we should allow that box to be either an "Overview" or an "Introduction" or a "Summary" -- depending on the content of the page. Or maybe not because that would be inconsistent.

Anyway, I think it is much lower priority than other things we need to spend out time on -- and I don't want to be distracted by it. :-)
