### ISSUE TITLE
Planning - Checklists Subheads

### ISSUE THREAD

**Issue by RachelComerford** [w3c/wai-media-guide#69]
Based on the heading structure it seems inconsistent that "Inform Users When Not Needed" didn't make it into the Checklist subhead list on Page Contents... without it, "Provide Both Captions and..." seems out of place on the list.

**Comment by shawna-slh** [comment]
Hi @RachelComerford ! Great to see that you are reviewing this resource!

Yeah, I wanted "Provide Both Captions and a Transcript" to be in the Page Contents at the top, because it was a specific question that we identified in the requirements analysis. (and informing users is not as important)

I re-did several aspects of the page headings, and now it makes sense to have only the h2-level headings in the Page Contents list. So it's no longer an issue. :-)
