### ISSUE TITLE
images proposed resolutions on big images

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#93]
(This is related to https://github.com/w3c/wai-website/issues/568 , yet I didn't want to add clutter to that issue, so opened this issue instead.)

**Please see the images under [How to Make Audio and Video Accessible](https://wai-media-guide.netlify.com/design-develop/media/#how-to-make-audio-and-video-accessible)**

Note: These are still drafts. Once we decide on the concepts, then the graphic artist will polish them up to have similar line widths, visual weight, etc.

EOWG previously agreed on the concepts for these images:
1. Audio Description of Visual Information
2. Captions/Subtitles
3. Transcripts
4. Sign Languages
5. Media player

Two new images are available for review under [How to Make Audio and Video Accessible](https://wai-media-guide.netlify.com/design-develop/media/#how-to-make-audio-and-video-accessible):

6. **Planning Audio and Video Media** - based on the [map image used in other Plan page](https://www.w3.org/WAI/planning-and-managing/plan/)<br><img width="70" alt="planning" src="https://user-images.githubusercontent.com/6991814/63064848-fbdfde00-bec8-11e9-8afe-fad2ec051769.png">

7. **Audio Content and Video Content** - covering [creating new content](https://wai-media-guide.netlify.com/design-develop/media/av-content/)<br><img width="79" alt="av-content" src="https://user-images.githubusercontent.com/6991814/63064854-039f8280-bec9-11e9-8fa9-9d031a27a48e.png">

**PROPOSED RESOLUTION: Use these 7 images.**

<hr>

New concepts for another image are right aligned with and under the heading:
8. [Transcribing Audio to Text](https://wai-media-guide.netlify.com/design-develop/media/transcribing/)

Options:
8.a. Don't have an image with this page. (It's conceptually different than the other pages.)
8.b. Use the speaker|hello concept: <img width="75" alt="transcribing" src="https://user-images.githubusercontent.com/6991814/63061852-460e9280-bebc-11e9-80a5-6ebcf50d014f.png">
8.c. Use the sound waves|hello concept: <img width="70" alt="transcribing-1" src="https://user-images.githubusercontent.com/6991814/63061883-6a6a6f00-bebc-11e9-8ca3-59a2240719f2.png">
8.d. **Try other concepts, for example:**
8.d.1. change "hello" to "text"
8.d.2. try replacing "hello" with a keyboard
8.d.3. something else...

We are very tight on budget for the graphics for this resource. (We're not going to get all that we listed in https://github.com/w3c/wai-website/issues/568 ) Therefore, I propose that for this version of the resource we go option 8.a. Don't have an image with this page.

**PROPOSED RESOLUTION: No image for 8 for this release.**

**Comment by yatil** [comment]
**Agree to the resolutions, no need to change.** However, of course, some comments:

* Planning Audio and Video Media – This icon looks like it is not square, which is desirable when used in a list of icons. Otherwise the icons feel unbalanced.

* Audio Content and Video Content – That one has many details and we’re using the icons in such small sizes (max. 75px) that it might be better with some simplification, at least when used in those really tiny sizes. Maybe just have the microphone and the camera cropped: 
![close up showing just the camera and the microphone](https://user-images.githubusercontent.com/58862/63079178-f53f7e00-bf3d-11e9-9e0a-c7e22904409f.png)

* I like the ideas for 8b and 8c, the lines in 8c should have the same width, and fewer of them to make it more clear. having a word in the icon means translations challenges (unless we define “hello” universally understandable and don’t translate it). Hello needs to be in the WAI typeface, Noto. There needs to be more space between the sound waves and the hello. I don’t like the wall between the speaker and the word in 8b. (What’s probably not possible in that small space is to have the sound waves look like an arrow.)

**Comment by cochfarf** [comment]
Agree to the resolutions.
Comments to Eric's comments :)
- Planning Audio and Video Media – the map icon isn't square (140px x 97px), but neither is the AD image (160px x 95px) or the CC image (127px × 87px). So I think that as long as the scaled width is the same for all images it should be fine.

- I'm OK with the original or the proposed simplification

- I like 8b and 8c as well. Agree there should be more space between the word and the sound waves and the word. Is "Hello World" something understood beyond old English speaking programmers?

**Comment by sharronrush** [comment]
- I think we *should* have an image here due to the media nature of the topic. That said, are we choosing between 8b and 8c? My very strong preference is for 8b. The speaker image is familiar and the concept is quite clear. 8c is more easily confusing and distracting.

- also strong preference for the zoomed in camera and microphone

**Comment by vmmiller** [comment]
Planning and audio image:  I'm not fully convinced by it but I don't have a better idea.  I'll leave it to the decision of the group.
Audio content and video content:  Good
Transcribing audio to text :  My preference is for 8b.  Simple and clear.

**Comment by bakkenb** [comment]
Planning and audio image: I like the map icon
Audio content and video content: I like the uncropped version, but okay with cropped version as well.
Transcribing audio to text : I like 8b.  8d1 and 8d2 seem like they could get confused with meaning speach to text.

**Comment by shawna-slh** [comment]
Resolutions accepted in [16 August 2019 EOWG teleconference](https://www.w3.org/2019/08/16-eo-minutes.html#item01)
